/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import AutoMiraj.View.Admin_int;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rumesha
 */
public class Backup_Restore extends javax.swing.JFrame {

    /**
     * Creates new form Backup_Restore
     */
    public Backup_Restore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_backup = new javax.swing.JTextField();
        btn_b_browse = new javax.swing.JButton();
        btn_backup = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_r_browse = new javax.swing.JButton();
        txt_restore = new javax.swing.JTextField();
        btn_restore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 540, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 29)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("BackUp and Restore");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 80, 310, 60);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Backup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 204, 255))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);
        jPanel5.add(txt_backup);
        txt_backup.setBounds(10, 70, 350, 30);

        btn_b_browse.setText("Browse...");
        btn_b_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b_browseActionPerformed(evt);
            }
        });
        jPanel5.add(btn_b_browse);
        btn_b_browse.setBounds(390, 70, 90, 30);

        btn_backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backup.png"))); // NOI18N
        btn_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backupActionPerformed(evt);
            }
        });
        jPanel5.add(btn_backup);
        btn_backup.setBounds(140, 120, 220, 240);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(40, 140, 490, 380);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restore", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 204, 255))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        btn_r_browse.setText("Browse...");
        btn_r_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_r_browseActionPerformed(evt);
            }
        });
        jPanel6.add(btn_r_browse);
        btn_r_browse.setBounds(400, 70, 90, 30);
        jPanel6.add(txt_restore);
        txt_restore.setBounds(20, 70, 360, 30);

        btn_restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restore.png"))); // NOI18N
        btn_restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restoreActionPerformed(evt);
            }
        });
        jPanel6.add(btn_restore);
        btn_restore.setBounds(160, 120, 220, 240);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(600, 140, 510, 380);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundNew.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_b_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b_browseActionPerformed
        // this is the browse button to backup files
        JFileChooser ch=new JFileChooser();
        ch.setSelectedFile(new File("*.sql")); // saving the backup file with the extension ".sql"
        ch.showOpenDialog(null);
        File f=ch.getSelectedFile();
        
        String file=f.getAbsolutePath();
        txt_backup.setText(file); // after giving the path its saving the backup file. 
    }//GEN-LAST:event_btn_b_browseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Admin_int ad = new Admin_int();
       ad.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_r_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_r_browseActionPerformed
        // This is the browse button to restore data 
        JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(null);
        File f=ch.getSelectedFile(); // browser will open a dialog box and allow user to select a file.
        String file=f.getAbsolutePath();
        txt_restore.setText(file); //then selected file's path will show in the text area
    }//GEN-LAST:event_btn_r_browseActionPerformed

    private void btn_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backupActionPerformed
        // this is the backup code 
        String file1=txt_backup.getText();
        if(file1.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please browse a path");
        }
        else if(file1!=""){
            try {
                int processComplete; // to verify that either process completed or not
                Process runtimeProcess = Runtime.getRuntime().exec("C:\\wamp\\bin\\mysql\\mysql5.5.16\\bin\\mysqldump -u root auto miraj -r "+file1);
                JOptionPane.showMessageDialog(null,"\n Backup created Successfully..\n Check the Backup File in "+file1);
                // call the mysqldump in terminal and execute it
                processComplete = runtimeProcess.waitFor();
                //this.updateTable();
                
            } //store the state in variable
            catch (IOException ex) {
                Logger.getLogger(Backup_Restore.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Backup_Restore.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_btn_backupActionPerformed

    private void btn_restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restoreActionPerformed
        // The restore code
        try{
            String databaseName="auto miraj";//database name
            String userName="root";//username of mysql
            //There is no any database password
            String source=txt_restore.getText();
            int processComplete;// this variable for verify the process
            if(source.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please browse a path");
            }
            else if(source!=""){
                String[] executeCmd = new String[]{"C:\\wamp\\bin\\mysql\\mysql5.5.16\\bin\\mysql", databaseName, "-u" + userName, "-e", " source "+source };
                //sava the command in a array
                Process runtimeProcess = Runtime.getRuntime().exec(executeCmd);// execute the command

                processComplete = runtimeProcess.waitFor();// get the result to variable
    
                JOptionPane.showMessageDialog(null, "Restore Completed");
            
                //dispose();
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_btn_restoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Backup_Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Backup_Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Backup_Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Backup_Restore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Backup_Restore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_b_browse;
    private javax.swing.JButton btn_backup;
    private javax.swing.JButton btn_r_browse;
    private javax.swing.JButton btn_restore;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txt_backup;
    private javax.swing.JTextField txt_restore;
    // End of variables declaration//GEN-END:variables
}
