/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import AutoMiraj.View.billStock;
import AutoMiraj.View.bill_details;
import AutoMiraj.View.AM_SMS;
import AutoMiraj.Controller.ServiceContaller;
import AutoMiraj.DBconnect.DBConnection;
import AutoMiraj.Model.BillStock;
import AutoMiraj.Model.CusBill;
import AutoMiraj.Model.ItemMove;
import AutoMiraj.Model.Service;
import AutoMiraj.View.billStock;
import AutoMiraj.View.bill_details;
import AutoMiraj.View.login;
import AutoMiraj.View.main_gui;
import SMSGateway.SMS;
import com.toedter.calendar.JDateChooser;
//import AutoMiraj.Model.main_gui;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElementDecl;

/**
 *
 * @author Deshan
 */
public class Bill_interface extends javax.swing.JFrame {

    /**
     * Creates new form Bill_interface
     */
    public Bill_interface() {
        initComponents();
        fillcombonames();
        fillcombonames1();
        //fillcombonames2();
        loginindicate();
      // getcurrentdate();
    }
        public  void loginindicate(){
        
          try {   
            String sql = "Select UserType from users where username='ashen'";
            Connection conn = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm = conn.prepareStatement(sql);
            
            ResultSet rst1 = stm.executeQuery(sql);
          
            while (rst1.next()) {
                String user = rst1.getString(1);
                
                 
             jLabel20.setText("<<<<"+(user)+" is login>>>>");
             date_bill.setText(getcurrentdate());
             
            }


        } 
        catch (SQLException e) {
            System.err.println(e);
        } catch (ClassNotFoundException ex) {
            System.err.println(ex);
        }
        
       
        
       

    }
        
        private String getcurrentdate(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        return(dateFormat.format(cal.getTime()));
        
    }

    public void formValidation() {
        if (jComboBox1.getSelectedItem().toString().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please select service");
            jComboBox1.requestFocus();
        } else if (jTextField3.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please add quantity");
            jTextField3.requestFocus();
        } else if (jTextField3.getText() == "^[0-9]") {
            JOptionPane.showMessageDialog(this, "Please check quantity");
            jTextField3.requestFocus();
        } else if (jComboBox4.getSelectedItem().toString().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please select item name");
            jComboBox4.requestFocus();
        } else if (jTextField11.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please add quantity");
            jTextField11.requestFocus();
        } else if (jTextField11.getText() == "^[0-9]") {
            JOptionPane.showMessageDialog(this, "Please check quantity");
            jTextField11.requestFocus();
        } else if (jComboBox2.getSelectedItem().toString().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please select vehicle no");
            jComboBox2.requestFocus();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        V_noIndecate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        date_bill = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        resCashIndicater = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        distxt = new javax.swing.JTextField();
        rescashtxt = new javax.swing.JTextField();
        returntxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jalabedis = new javax.swing.JLabel();
        ComboDis = new javax.swing.JComboBox();
        withoutDistxt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        indicate1 = new javax.swing.JLabel();
        indicate2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField12 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        indicateItem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        servIndicate = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        billTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Customer Bill");

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        V_noIndecate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        V_noIndecate.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(V_noIndecate);
        V_noIndecate.setBounds(690, 266, 240, 20);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(730, 260, 2, 2);

        jPanel9.setBackground(new java.awt.Color(51, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setOpaque(false);

        date_bill.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date_bill.setForeground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date_bill, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date_bill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(310, 380, 370, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1040, 0, 110, 30);

        jPanel8.setBackground(new java.awt.Color(153, 255, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Balancing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 255, 255))); // NOI18N
        jPanel8.setOpaque(false);

        resCashIndicater.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resCashIndicater.setForeground(new java.awt.Color(255, 51, 0));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Discount amount :");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Reserved Cash  :");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Retrurn Cash     :");

        distxt.setBackground(new java.awt.Color(0, 0, 0));
        distxt.setFont(new java.awt.Font("Segoe Script", 0, 13)); // NOI18N
        distxt.setForeground(new java.awt.Color(255, 255, 255));

        rescashtxt.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N

        returntxt.setBackground(new java.awt.Color(0, 0, 0));
        returntxt.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        returntxt.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Change Discount   (%)           :  ");

        jalabedis.setForeground(new java.awt.Color(153, 255, 0));

        ComboDis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ComboDis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "5", "15" }));

        withoutDistxt.setBackground(new java.awt.Color(0, 0, 0));
        withoutDistxt.setFont(new java.awt.Font("Segoe Script", 0, 13)); // NOI18N
        withoutDistxt.setForeground(new java.awt.Color(255, 255, 255));
        withoutDistxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withoutDistxtActionPerformed(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Without discount :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(withoutDistxt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jalabedis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rescashtxt)
                                    .addComponent(returntxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))
                                    .addComponent(distxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(12, 12, 12))
                    .addComponent(resCashIndicater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ComboDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withoutDistxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(2, 2, 2)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jalabedis, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resCashIndicater, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rescashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(returntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(930, 380, 350, 310);

        jPanel6.setBackground(new java.awt.Color(255, 0, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message Box", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel6.setToolTipText("");
        jPanel6.setOpaque(false);

        jLabel19.setFont(new java.awt.Font("T02ThibusTru", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Location Indicator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel7.setOpaque(false);

        jLabel22.setFont(new java.awt.Font("T02ThibusTru", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));

        jLabel21.setFont(new java.awt.Font("T02ThibusTru", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        indicate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        indicate1.setForeground(new java.awt.Color(255, 0, 0));

        indicate2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        indicate2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indicate1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(indicate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(indicate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indicate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(940, 30, 330, 340);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log out.png"))); // NOI18N
        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1160, 0, 110, 30);

        jPanel5.setBackground(new java.awt.Color(0, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setOpaque(false);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sms3.JPG"))); // NOI18N
        jButton7.setText("S         M          S");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ss.JPG"))); // NOI18N
        jButton9.setText("Services Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_bill.JPG"))); // NOI18N
        jButton12.setText("New Bill");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calc.JPG"))); // NOI18N
        jButton5.setText("CALCULATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/word.JPG"))); // NOI18N
        jButton6.setText("GENARATE BILL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gen bill.JPG"))); // NOI18N
        jButton2.setText("Bill List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(70, 550, 380, 140);

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setOpaque(false);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe Script", 0, 70)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("T10ThibusTru", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("Total");

        jLabel18.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 255, 255));
        jLabel18.setText("Rs:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(24, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(86, 86, 86))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(460, 550, 470, 140);

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Item issued" }));
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Select");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Item Id");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("amount");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Quantity");

        indicateItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        indicateItem.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicateItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox4, 0, 183, Short.MAX_VALUE)
                    .addComponent(jTextField10)
                    .addComponent(jTextField12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(indicateItem)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(510, 30, 430, 210);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Services", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select service" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Service ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Service No");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Amount");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qunatity");

        servIndicate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        servIndicate.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(servIndicate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(servIndicate)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(70, 30, 410, 210);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        jButton11.setText(" Remove Row");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(780, 380, 150, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select vehicle number" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(310, 260, 370, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vehicle No");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 270, 70, 10);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(310, 350, 370, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bill No");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 290, 60, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service No or Item Id", "Service type or replace part name", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 410, 860, 130);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(310, 320, 370, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(310, 290, 370, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("       THE CUSTOMER BILL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 0, 260, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 330, 60, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 360, 100, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 390, 60, 14);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fun_back_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        billTextArea1.setColumns(20);
        billTextArea1.setRows(5);
        jPanel1.add(billTextArea1);
        billTextArea1.setBounds(680, 0, 590, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
      try{ 
            String nic2 = jTextField8.getText();
            String sql = "Select cphone,cnmilage from customer where cnic='"+nic2+"'";
         
            
            Connection conn = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm = conn.prepareStatement(sql);
         
            ResultSet rst1 = stm.executeQuery(sql);
          
          
            while (rst1.next()) {
                String pnum = rst1.getString(1);
              
                String Nmilage = rst1.getString(2);
                
                String V_no = jComboBox2.getSelectedItem().toString();
                String bill_no = jTextField5.getText();
               // String name = jTextField6.getText();
                   String customerName2 = jTextField6.getText();
                String c_id = jTextField8.getText();
                String total= jTextField2.getText();
                String date = date_bill.getText();
             
                

                System.out.println(pnum);
             
                String msg="Auto Miraj Servistaion mount lavenia"+"\n"+
                            "\n"+
                            "Date         :"+date+"\n"+
                            "Vehicle No   :"+V_no+"\n"+
                            "bill No      :"+bill_no+"\n"+
                            "Total amount :"+total+"\n"+
                            "\n"+
                            
                           "Your next milage is : "+Nmilage+"\n"+
                           "Thank you come again..!";
                                       
                System.out.println(msg);
                 
             
                
                indicate2.setText(customerName2);
                 //String totaltt= jTextField2.getText();
              String h=   jComboBox2.getSelectedItem().toString();
                if(total.isEmpty()&& h.equals("Select vehicle number") ){
                jLabel19.setText("Unsucceful Attemp!");
                
            }
                else{
                  
                    SMS sms = new SMS();
                
                    sms.sendSms(pnum,msg);
                    
                      jLabel19.setText("2)You have sent a SMS to ");
                      indicate2.setText(customerName2);
                    
                }
            
          
                
            }} catch (ClassNotFoundException ex) {
            Logger.getLogger(Bill_interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Bill_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void fillcombonames() {
        ServiceContaller sc = new ServiceContaller();
        ArrayList sname = sc.getServiceType();
        Iterator i = sname.iterator();

        while (i.hasNext()) {
            jComboBox1.addItem(i.next());

        }
        
      // String date=getcurrentdate();
      // int dd = Integer.parseInt(date);
      // Date date= new Date();
       // Date date1 = (03/07/2011);
       // Date date2 = date.subtractNumberOfDays( 7);
       
    }

    private void fillcombonames1() {
        ServiceContaller sc1 = new ServiceContaller();
      
        String date=getcurrentdate();
        ArrayList sname1 = sc1.getVehicleNo(date);
        Iterator i1 = sname1.iterator();

        while (i1.hasNext()) {
            jComboBox2.addItem(i1.next());
            
            
           // System.out.println(i1.next());

        }
    }

    private void fillcombonames2() {
        ServiceContaller sc1 = new ServiceContaller();
        String v_no = jComboBox2.getSelectedItem().toString();
        String date=getcurrentdate();
        ArrayList sname2 = sc1.getItemType(date,v_no);
        Iterator i2 = sname2.iterator();

        while (i2.hasNext()) {
            jComboBox4.addItem(i2.next());

        }


    }
    
 /*  public  void loginindicate(String name){
        
          try {
            String sql = "Select UserType from users where username='"+name+"'";
            Connection conn = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm = conn.prepareStatement(sql);
            
            ResultSet rst1 = stm.executeQuery(sql);
          
            while (rst1.next()) {
                String user = rst1.getString(1);
                
                 
             jLabel20.setText("<<<<"+(user)+" is login>>>>");
            }


        } 
        catch (SQLException e) {
            System.err.println(e);
        } catch (ClassNotFoundException ex) {
            System.err.println(ex);
        }
        
        
        
    }*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //formValidation();
  
        String fl = jComboBox1.getSelectedItem().toString();
        String fl2 = jTextField3.getText();


        if (fl.equals("Select service")) {
            servIndicate.setText("Please select a service!");
        } else if (fl2.length() == 0) {
            //JOptionPane.showMessageDialog(null, "Quantity should not be empty");
            servIndicate.setText("Quantity should not be empty!");
        } else {
            try {
                String SerType = (String) jComboBox1.getSelectedItem();
                String Seramount = jTextField3.getText();
                String SerID = jTextField1.getText();
                String Serquantity = jTextField7.getText();
                DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
                mod.addRow(new Object[]{SerID, SerType, Seramount, Serquantity});
                servIndicate.setText("");
            } catch (Exception e) {
                System.out.print(e);
            }

            {
            }


        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        main_gui M = new main_gui();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        bill_details bb = new bill_details();
        bb.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Bill_interface bill = new Bill_interface();
        bill.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        double total = 0;
        double qq = 0;
        double sum = 0;
        double ww = 0;
        int nRow = dtm.getRowCount();

        for (int i = 0; i < nRow; i++) {
            qq = (Double.parseDouble(jTable1.getValueAt(i, 2).toString()));
            total = (Double.parseDouble(jTable1.getValueAt(i, 3).toString()));
            ww = (qq * total);
            sum = (sum + ww);
        }
      //discunt make----------------------------------------------------------------
         try {
             
            String nic2 = jTextField8.getText();
            String sql = "Select COUNT(upto) from customer where cnic='"+nic2+"'";
            Connection conn = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm = conn.prepareStatement(sql);
            
            ResultSet rst1 = stm.executeQuery(sql);
          
            while (rst1.next()) {
                String No = rst1.getString(1);
                int No1 = Integer.parseInt(No);
                
           double dis=0;
           double sumfinal =0;
           
           
                   if(No1>=2 )    
         {
            
           String disP = ComboDis.getSelectedItem().toString();
           int disPrsnt = Integer.parseInt(disP);
           dis=(sum*disPrsnt/100);
           
           distxt.setText(Double.toString(dis));
           jalabedis.setText("costomer's all records is  : "+No1);
           withoutDistxt.setText(Double.toString(sum));
           sumfinal =(sum-dis);
           jTextField2.setText(Double.toString(sumfinal));
           
           
        }
        else 
                   {
            jTextField2.setText(Double.toString(sum));
          
                   }
            }


        } 
        catch (SQLException e) {
            System.err.println(e);
        } catch (ClassNotFoundException ex) {
            System.err.println(ex);
        }

        
        
      







    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String serv_type = jComboBox1.getSelectedItem().toString();

        try {
            Service serv = ServiceContaller.searchServiceType(serv_type);
            if (serv != null) {
                jTextField1.setText(serv.getSerId());
                jTextField7.setText(Double.toString(serv.getSerAmount()));
            } else {
                //JOptionPane.showMessageDialog(this, "No Service found..");
                servIndicate.setText("Please select a service!");
            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            // Logger.getLogger(bill_details.class.getSerId()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(bill_details.class.getSerType()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
     
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        setBillNumber();
       
        String vehicleNumber = jComboBox2.getSelectedItem().toString();
         
        try {

            CusBill cb = ServiceContaller.searchCusDetails(vehicleNumber);
            if (cb != null) {

                jTextField6.setText(cb.getNic());
                jTextField8.setText(cb.getCusName());
                 V_noIndecate.setText("");

            } else {
               // JOptionPane.showMessageDialog(this, "No Service found..");
               V_noIndecate.setText("Please select the vehicle number!");

            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            // Logger.getLogger(bill_details.class.getSerId()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.out.println(ex);
    }//GEN-LAST:event_jComboBox2ActionPerformed
    fillcombonames2();
    }
    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        fillcombonames2();       
        
       
    }//GEN-LAST:event_jComboBox2MouseClicked
    
   
       
                
             
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String fl = jComboBox4.getSelectedItem().toString();


          if(fl.equals("Select Item issued")){
              
        // JOptionPane.showMessageDialog(null, "Please select a service");
               indicateItem.setText("Please select a item issued!");
         }
         


         else{
        try {
            String itemType = (String) jComboBox4.getSelectedItem();
            String itemamount = jTextField10.getText();
            String itemID = jTextField12.getText();
            String itemquantity = jTextField11.getText();
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            mod.addRow(new Object[]{itemID, itemType, itemquantity, itemamount});
             indicateItem.setText("");
        } catch (Exception e) {
            System.out.print(e);
        }

        {
        }



         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      //try{ 
           
           String de=rescashtxt.getText();
           String numeric="[0-9]+";
         
         if(de.isEmpty())
           { 
             resCashIndicater.setText("Please enter Received chash amount!");
            
           } 
       else  if(!de.matches(numeric)){  
           
           
           resCashIndicater.setText("Please enter Numeric Value!");
           rescashtxt.setText(null);
         }
         else{
            
            double res_cash = Double.parseDouble(rescashtxt.getText());
           double total_am = Double.parseDouble(jTextField2.getText());
          
            if(res_cash<total_am){
            resCashIndicater.setText("Please enter value greater than total amount");
            
            }
            else{
                
                double return_cash;
            return_cash=(res_cash-total_am);
            returntxt.setText(Double.toString(return_cash));
            resCashIndicater.setText("");
            }
           
           
           
         }
           
           
            
         
         
         
//}
             
          // catch (Exception exxx2) {
         //   System.out.println(exxx2);
    
//}
        try{ //the file path
            String sql = "Select MAX(cbill_no) from cus_bill";
            Connection conn = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm = conn.prepareStatement(sql);
            
            ResultSet rst1 = stm.executeQuery(sql);
          
            while (rst1.next()) {
                String No = rst1.getString(1);
                int No1 = Integer.parseInt(No);
                int No2= (No1+1);
            
              
             //File file = new File("C:\\Users\\Deshan\\Desktop\\Auto miraj bill inventory\\"+No2+".doc") ;
             //if the file not exist create one
            // if(!file.exists()){ file.createNewFile(); 
             
            
       // } FileWriter fw = 
           // fw = new FileWriter(file.getAbsoluteFile());
        // BufferedWriter bw = new BufferedWriter(fw);
         
       //  Bill_interface er=new Bill_interface();
        //   er.setVisible(true); 
         
            billTextArea1.append ("                           AUTO MIRAJ SERVICE CENTER");
            billTextArea1.append ("\n");
            billTextArea1.append ("                                Mount Lavenia");
            billTextArea1.append ("\n");
            billTextArea1.append ("                          Tel : 011-2884562/0777185269");
            billTextArea1.append ("\n");
            billTextArea1.append ("                          Email : AutoMiraj@gmail.com ");
          
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            
            int cbillNo =  Integer.parseInt(jTextField5.getText());
            billTextArea1.append ("Bill No          :"+ cbillNo);
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            
            String vehicleNumber2 = jComboBox2.getSelectedItem().toString();
            billTextArea1.append("Vehicle Number   :"+vehicleNumber2);
            billTextArea1.append("\n");
            billTextArea1.append ("\n");
             
           String date=getcurrentdate();
            billTextArea1.append ("Date             :"+ date);
            billTextArea1.append("\n");
            billTextArea1.append ("\n");
            
            String customerName2 = jTextField6.getText();
            billTextArea1.append ("Customer Name    :"+ customerName2);
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            
            String nic2 = jTextField8.getText();
            billTextArea1.append ("Customer NIC No  :"+ nic2);
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            
           
            billTextArea1.append("________________________SERVICE DETAILS_____________________________");
            billTextArea1.append ("\n");
            billTextArea1.append ("\n");
            
            billTextArea1.append("Service Type or replace item name| Qunatity      |      Amount (Rs:)");
            billTextArea1.append("\n");
          
            billTextArea1.append("\n");
            
            
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        int nRow=dtm.getRowCount();
        int nCol=dtm.getColumnCount();
        Object[][] tableData=new Object[nRow][nCol];
        for(int i=0; i<nRow; i++)
        {
            for(int j=1; j<nCol; j++)
            {
                tableData[i][j]=dtm.getValueAt(i, j);
                billTextArea1.append(tableData[i][j].toString()+"\t\t");
            }
            billTextArea1.append("          \n");
        }
        
    
            billTextArea1.append ("\n");
           
            
            billTextArea1.append("\n");
            double ctotal = Double.parseDouble(jTextField2.getText());
            billTextArea1.append("____________________________________________________________________");
            billTextArea1.append("\n");
            billTextArea1.append("                                 Amount of services is Rs   : "+ctotal);
            
            billTextArea1.append("\n");
            
             if(withoutDistxt.getText().length()==0){
                 
             try{
                  String nic22 = jTextField8.getText();
            String sql2 = "Select COUNT(upto) from customer where cnic='"+nic22+"'";
            Connection conn2 = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm2 = conn2.prepareStatement(sql2);
            
            ResultSet rst12 = stm2.executeQuery(sql2);
          
            while (rst12.next()) {
                String No_2 = rst12.getString(1);
              
                billTextArea1.append("                                 your records of attending  : "+No_2);
                billTextArea1.append("\n");
                billTextArea1.append("                                 your dicount               :  0.0");
                
            }
           
             }
             
             catch (Exception exxx2) {
            System.out.println(exxx2);
        }}
             
             else { String NoAtd = jalabedis.getText();
                    String disC=distxt.getText();
                    billTextArea1.append("                                 "+NoAtd);
                    billTextArea1.append("\n");
                    billTextArea1.append("                                 Your dicount Rs            : "+disC);
                  }
              String rescash=rescashtxt.getText();
              String returnchash=returntxt.getText();
              String tot_final = jTextField2.getText();
              
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("                                 Total amount Rs            : "+tot_final);
            billTextArea1.append("\n");
            billTextArea1.append("                                 Received chash Rs          : "+rescash);
            billTextArea1.append("\n");
            billTextArea1.append("                                 Returen chash Rs           : "+returnchash);
            billTextArea1.append("\n");
            billTextArea1.append("____________________________________________________________________");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("If you have come more than 3 terms to Auto miraj,you have discount 10%.");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("                         Thank you come again...!");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append("\n");
            billTextArea1.append ("                 (all right of print document @ atouo miraj cashier)");
            
            
           
           
         //   bw.close();
          //   fw.close();
               }
         }catch(Exception ex){
                   ex.printStackTrace();
               }
        
        double res_cash = Double.parseDouble(rescashtxt.getText());
        double total_am = Double.parseDouble(jTextField2.getText());
        String f4 = jComboBox2.getSelectedItem().toString();
        
        if (f4.equals("Select vehicle number")){
            
               V_noIndecate.setText("Please select the vehicle number!");
        }
       else if((res_cash<total_am)){
            System.out.println("res_cash");
        }
        else{      try{
            
        
            
            boolean complete=billTextArea1.print();
            if(complete){
               
                JOptionPane.showMessageDialog(null, "Done printing", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Printing", "Printer", JOptionPane.ERROR_MESSAGE);
            }
        }
            catch(PrinterException e){
           
            JOptionPane.showMessageDialog(null, e);
        }
        
        
         //String vNumber=Reservoir.No2.getText();
        int cbillNo1 =  Integer.parseInt(jTextField5.getText());
        try{
            FileWriter writer=new FileWriter("C:\\Users\\Amith\\Desktop\\Auto miraj bill inventory\\bill_"+cbillNo1+".doc");
            BufferedWriter bw = new BufferedWriter(writer);
            billTextArea1.write(bw);
            billTextArea1.requestFocus();
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        

        try {


            int cbillNo =  Integer.parseInt(jTextField5.getText());
           
            String date=getcurrentdate();
            String vehicleNumber2 = jComboBox2.getSelectedItem().toString();
            String customerName2 = jTextField6.getText();
            String nic2 = jTextField8.getText();
            double ctotal = Double.parseDouble(jTextField2.getText());

            BillStock BS = new BillStock(cbillNo, date, vehicleNumber2, customerName2, nic2, ctotal);
            int res = ServiceContaller.addBillstock(BS);
            if (res > 0) {
               
                indicate1.setText("1)This bill was added to the bill list.");
               
                
                jLabel21.setText("Customer copy of bill number: "+(cbillNo) +" is ");
                jLabel22.setText("added to the 'Auto miraj bill inventory' folder!");
            }
        } catch (Exception exxx) {
            System.out.println(exxx);
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        billStock bbb = new billStock();
        bbb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

       String item_type = jComboBox4.getSelectedItem().toString();
       String v_no = jComboBox2.getSelectedItem().toString();
       String date=getcurrentdate();
       
        try {
            ItemMove MI = ServiceContaller.SelectItem(item_type,v_no,date);
            if (MI != null) {
                jTextField12.setText(MI.getitem_id());
                jTextField10.setText(Float.toString(MI.getselling_price()));
                jTextField11.setText(Float.toString(MI.getquantity()));
            } else {
                JOptionPane.showMessageDialog(this, "No Service found..");
            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            // Logger.getLogger(bill_details.class.getSerId()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(bill_details.class.getSerType()).log(Level.SEVERE, null, ex);
        
    }//GEN-LAST:event_jComboBox4ActionPerformed
    }
    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
     

    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
  
        
        DefaultTableModel modelTable = (DefaultTableModel) jTable1.getModel();
  
        int SelectedRow = jTable1.getSelectedRow();
 
        modelTable.removeRow(SelectedRow);




    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void withoutDistxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withoutDistxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withoutDistxtActionPerformed
     
    // Bill number setting*************
            
       private void setBillNumber(){
        try {
            String sql = "Select MAX(cbill_no) from cus_bill";
            Connection conn = DBConnection.getDBConnection().getConnection();
            PreparedStatement stm = conn.prepareStatement(sql);
            
            ResultSet rst1 = stm.executeQuery(sql);
          
            while (rst1.next()) {
                String No = rst1.getString(1);
                int No1 = Integer.parseInt(No);
                int No2= (No1+1);
                 
               jTextField5.setText(Integer.toString(No2));
            }


        } 
        catch (SQLException e) {
            System.err.println(e);
        } catch (ClassNotFoundException ex) {
            System.err.println(ex);
        }

  // *******************************************************************   
    }
          
          
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_interface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboDis;
    private javax.swing.JLabel V_noIndecate;
    private javax.swing.JTextArea billTextArea1;
    private javax.swing.JLabel date_bill;
    private javax.swing.JTextField distxt;
    private javax.swing.JLabel indicate1;
    private javax.swing.JLabel indicate2;
    private javax.swing.JLabel indicateItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel jalabedis;
    private javax.swing.JLabel resCashIndicater;
    private javax.swing.JTextField rescashtxt;
    private javax.swing.JTextField returntxt;
    private javax.swing.JLabel servIndicate;
    private javax.swing.JTextField withoutDistxt;
    // End of variables declaration//GEN-END:variables
}
