/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import AutoMiraj.Controller.ServiceContaller;
import AutoMiraj.Model.BillStock;
import AutoMiraj.Model.Service;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deshan
 */
public class billStock extends javax.swing.JFrame {

    /**
     * Creates new form billStock
     */
    public billStock() {
        initComponents();
        tableLoad();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        indicateBillmmeassage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        billnoS = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cusId = new javax.swing.JTextField();
        C_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        billDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        V_no = new javax.swing.JTextField();
        billNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 550));
        jPanel1.setLayout(null);

        indicateBillmmeassage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        indicateBillmmeassage.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(indicateBillmmeassage);
        indicateBillmmeassage.setBounds(30, 454, 440, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bill No   :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 430, 50, 14);

        billnoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnoSActionPerformed(evt);
            }
        });
        jPanel1.add(billnoS);
        billnoS.setBounds(440, 410, 90, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(180, 410, 100, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Name :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 310, 100, 14);
        jPanel1.add(cusId);
        cusId.setBounds(300, 350, 160, 30);

        C_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_nameActionPerformed(evt);
            }
        });
        jPanel1.add(C_name);
        C_name.setBounds(300, 300, 160, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer ID      :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 350, 100, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total         :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 350, 60, 14);
        jPanel1.add(totaltxt);
        totaltxt.setBounds(540, 350, 100, 30);
        jPanel1.add(billDate);
        billDate.setBounds(90, 350, 100, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bill date  :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 350, 60, 14);

        V_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_noActionPerformed(evt);
            }
        });
        jPanel1.add(V_no);
        V_no.setBounds(540, 300, 100, 30);
        jPanel1.add(billNo);
        billNo.setBounds(90, 300, 100, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehicle No  :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 310, 70, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bill No      :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 310, 60, 14);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(580, 450, 100, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill List");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 40, 170, 22);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 410, 110, 30);

        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No", "Bill date", "Vehiclle No", "Customer Name", "Customer ID", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billtable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 630, 210);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fun_back_1.jpg"))); // NOI18N
        jLabel1.setText("Bill date");
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 550));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void tableLoad()
            
            
            
    { 
         try {
            ArrayList<BillStock> BSS = ServiceContaller.getBillStock();
            DefaultTableModel dtm=(DefaultTableModel) billtable.getModel();
            dtm.setRowCount(0);
            for (BillStock BS : BSS) {
                Object[] rowData={BS.getcbillNo(),BS.getCusDate2(),BS.getvehicleNumber2(),BS.getCusName2(),BS.getNic2(),BS.getctotal()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            System.out.println(ex);
}}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Bill_interface bill=new Bill_interface();
         // bill.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void V_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V_noActionPerformed

    private void C_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_nameActionPerformed

    private void billnoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billnoSActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String bill_id = billNo.getText();

        try {
            int res = ServiceContaller.delteBill(bill_id);
            if (res > 0) {
                //JOptionPane.showMessageDialog(this, "Delete success");
                indicateBillmmeassage.setText("Delete successfull...!");
            } else {
               // JOptionPane.showMessageDialog(this, "Delete Fail");
                 indicateBillmmeassage.setText("Delete Fail...!");
            }
        } catch (Exception ex) {
            System.out.println(ex);
            //Logger.getLogger(bill_details.class.getSerId()).log(Level.SEVERE, null, ex);
        } 
        
         try {
            ArrayList<BillStock> BSS = ServiceContaller.getBillStock();
            DefaultTableModel dtm=(DefaultTableModel) billtable.getModel();
            dtm.setRowCount(0);
            for (BillStock BS : BSS) {
                Object[] rowData={BS.getcbillNo(),BS.getCusDate2(),BS.getvehicleNumber2(),BS.getCusName2(),BS.getNic2(),BS.getctotal()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            System.out.println(ex);
            //Logger.getLogger(bill_details.class.getSerId()).log(Level.SEVERE, null, ex);
              
    }                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          String bil_id1 = billnoS.getText();
          int  bil_id2= Integer.parseInt(bil_id1);
        try { 
             //BillStock BS = new BillStock(bil_id);
            // int res = ServiceContaller.addBillstock(BS);
           BillStock BS = ServiceContaller.searchBill(bil_id2);
            if (BS != null) {
                cusId.setText(BS.getNic2());
                C_name.setText(BS.getCusName2());
                billDate.setText(BS.getCusDate2());
                billNo.setText(Integer.toString(BS.getcbillNo()));
                V_no.setText(BS.getvehicleNumber2());
                totaltxt.setText(Double.toString(BS.getctotal()));                
            } else {
                //JOptionPane.showMessageDialog(this, "No Service found..");
                 indicateBillmmeassage.setText(" Bill Details not found...!");
            }
        } catch (Exception ex) {
            System.out.println(ex);
           
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billStock().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_name;
    private javax.swing.JTextField V_no;
    private javax.swing.JTextField billDate;
    private javax.swing.JTextField billNo;
    private javax.swing.JTextField billnoS;
    private javax.swing.JTable billtable;
    private javax.swing.JTextField cusId;
    private javax.swing.JLabel indicateBillmmeassage;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
