/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import javax.swing.JOptionPane;
import AutoMiraj.DBconnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JDesktopPane;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;
import javax.swing.JTextField;

import AutoMiraj.Model.register;
import AutoMiraj.View.login;
import AutoMiraj.View.main_gui;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kusal Rodrigo
 */
public class Client_Reigstration extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst =  null;
    ResultSet rs = null;
    /**
     * Creates new form Client_Reigstration
     */
    public Client_Reigstration() {
        initComponents();
        
        con = DBconnect.connect();
        tableload();
    }
 
    public void tableload()
    {
        try {
           
            String sql1 = "SELECT * FROM customer";
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            infotable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        caddress = new javax.swing.JTextField();
        cmilage = new javax.swing.JTextField();
        vNumber = new javax.swing.JLabel();
        vnumber = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        cName = new javax.swing.JLabel();
        cphone = new javax.swing.JTextField();
        cPhone = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        nictxt = new javax.swing.JTextField();
        cMilage = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cEmail = new javax.swing.JLabel();
        cAddress = new javax.swing.JLabel();
        nMilage = new javax.swing.JLabel();
        nmilage = new javax.swing.JTextField();
        cname1 = new javax.swing.JTextField();
        cName1 = new javax.swing.JLabel();
        cPhone1 = new javax.swing.JLabel();
        cbrand = new javax.swing.JTextField();
        cmodel = new javax.swing.JTextField();
        cPhone2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infotable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Registration");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1275, 715));

        jPanel1.setOpaque(false);

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Client", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        caddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddressActionPerformed(evt);
            }
        });

        cmilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmilageActionPerformed(evt);
            }
        });
        cmilage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmilageKeyTyped(evt);
            }
        });

        vNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vNumber.setForeground(new java.awt.Color(255, 255, 255));
        vNumber.setText("Vehicle Number");

        vnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnumberActionPerformed(evt);
            }
        });

        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });

        cName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cName.setForeground(new java.awt.Color(255, 255, 255));
        cName.setText("NIC");

        cphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cphoneActionPerformed(evt);
            }
        });

        cPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cPhone.setForeground(new java.awt.Color(255, 255, 255));
        cPhone.setText("Phone Number");

        jButton3.setText("Add ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nictxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nictxtActionPerformed(evt);
            }
        });

        cMilage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cMilage.setForeground(new java.awt.Color(255, 255, 255));
        cMilage.setText("Current Milage");

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cEmail.setForeground(new java.awt.Color(255, 255, 255));
        cEmail.setText("Email");

        cAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cAddress.setForeground(new java.awt.Color(255, 255, 255));
        cAddress.setText("Address");

        nMilage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nMilage.setForeground(new java.awt.Color(255, 255, 255));
        nMilage.setText("Next Service due Milage");

        nmilage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmilageMouseClicked(evt);
            }
        });
        nmilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmilageActionPerformed(evt);
            }
        });

        cname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cname1ActionPerformed(evt);
            }
        });

        cName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cName1.setForeground(new java.awt.Color(255, 255, 255));
        cName1.setText("Name");

        cPhone1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cPhone1.setForeground(new java.awt.Color(255, 255, 255));
        cPhone1.setText("Brand");

        cbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrandActionPerformed(evt);
            }
        });

        cmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmodelActionPerformed(evt);
            }
        });

        cPhone2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cPhone2.setForeground(new java.awt.Color(255, 255, 255));
        cPhone2.setText("Model");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cName)
                            .addComponent(cName1))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cname1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cMilage)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cEmail)
                                    .addComponent(cPhone)
                                    .addComponent(cAddress)
                                    .addComponent(cPhone1)
                                    .addComponent(cPhone2)
                                    .addComponent(vNumber)))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(caddress, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(cphone)
                                .addComponent(cbrand)
                                .addComponent(cmodel)
                                .addComponent(vnumber))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nMilage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmilage, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(nmilage))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cName)
                    .addComponent(nictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cName1)
                    .addComponent(cname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAddress)
                    .addComponent(caddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cEmail)
                    .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPhone)
                    .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPhone1)
                    .addComponent(cbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cPhone2)
                    .addComponent(cmodel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cMilage)
                    .addComponent(cmilage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nMilage)
                    .addComponent(nmilage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Details", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        infotable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIC", "Name", "Address", "Email", "Phone Number", "Reg.Date", "Update Date", "Brand", "Model", "vehicle Number", "Current Mileage"
            }
        ));
        infotable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infotable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(infotable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vehicle Number or Customer Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Registration", jPanel1);

        jPanel2.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Vehicle Number or Customer Name");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Show the history");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History of Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Vehicle No", "Service", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel9)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("History", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 30, 1256, 644);

        jButton10.setText("Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(1121, 11, 55, 23);

        jButton9.setText("Log Out");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1194, 11, 71, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfaceBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
  
    
    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void cphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cphoneActionPerformed

    private void caddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddressActionPerformed

    private void nictxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nictxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nictxtActionPerformed

    private void vnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnumberActionPerformed

    private void cmilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmilageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmilageActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String srch = search.getText();
        
        try {
            String s1 =" SELECT cname,caddress,cemail,cphone,date,cvbrand,cvnumber,ccmileage FROM customer WHERE cvnumber LIKE '%"+srch+"%' OR cname LIKE '%"+srch+"%' ";
            pst = con.prepareStatement(s1);
            rs = pst.executeQuery();
            
            infotable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String n=nictxt.getText();
        String na=cname1.getText();
        String ad=caddress.getText();
        String em=cemail.getText();
        String pho=cphone.getText();
        String br=cbrand.getText();
        String mo=cmodel.getText();
        String no=vnumber.getText();
        String mil=cmilage.getText();
        
        boolean v = true;
        
        if(n.isEmpty()){
            v=false;
            JOptionPane.showMessageDialog(null, "NIC should not be empty!");
        }
        else if (n.length() != 10) {
            v= false;
            JOptionPane.showMessageDialog(null, "Invalid NIC number,NIC does not cotain 9 digits");
        } else if (!n.matches("[0-9]+v")) {
            v = false;
            JOptionPane.showMessageDialog(null, "Invalid NIC number format!");
        }

        
        if (na.isEmpty()) {
            v=false;
            JOptionPane.showMessageDialog(null, "Name should not be empty!");
        } 
        else if(!na.matches("[a-zA-Z]+")){
            v = false;
           JOptionPane.showMessageDialog(null, "Invalid name format!"); 
        }
          if(ad.isEmpty()){
            v=false;
            JOptionPane.showMessageDialog(null, "Address should not be empty!");
        }
        
             if (em.isEmpty()) {
           v= false;
            JOptionPane.showMessageDialog(null, "Customer's email should not be empty!");
        } 
             else if (em.indexOf("@") == -1 || !(em.endsWith(".com"))) {
            v= false;
            JOptionPane.showMessageDialog(null, "Invalid Email format!");
        }
        
           
        
         if (br.isEmpty()) {
            v=false;
            JOptionPane.showMessageDialog(null, "Brand should not be empty!");
    
       }
        else if(!br.matches("[a-zA-Z]+")){
            v= false;
           JOptionPane.showMessageDialog(null, "InvalidBrand format!"); 
        }
                    
         if (mo.isEmpty()) {
            v=false;
            JOptionPane.showMessageDialog(null, "Model should not be empty!");
        } 
                
         if(no.isEmpty()){
            v=false;
            JOptionPane.showMessageDialog(null, "Vehicle number should not be empty!");
        }
        
         if (mil.isEmpty()) {
            v =false;
            JOptionPane.showMessageDialog(null, "Milage should not be empty!");
        } 
         else if(mil.matches("[a-zA-Z]+")){
            v = false;
           JOptionPane.showMessageDialog(null, "Invalid milage format!"); 
        }       
        
        
      if(v) {
       
        register r1=new register();
       
        
        r1.setNic(nictxt.getText());
        r1.setCusName(cname1.getText());
        
        r1.setCusAddress(caddress.getText());
       
        r1.setCusemail(cemail.getText());
      
        r1.setCusPhoneNumber(cphone.getText());
       
      
        
        r1.setVehicleBrand(cbrand.getText());
        r1.setVehicleModel(cmodel.getText());
        
        r1.setVehicleNumber(vnumber.getText());
        int Cmilage = Integer.parseInt(cmilage.getText());
        r1.setCurrentMilage(Integer.parseInt(cmilage.getText()));
       
        r1.setNextServiceDueMilage(Cmilage + 5000);
        nmilage.setText(Integer.toString(Cmilage + 5000));
        
        String nic=r1.getNic();
        String Cname = r1.getCusName();
        String Caddress = r1.getCusAddress();
        String Cemail = r1.getCusemail();
        String Cphone = r1.getCusPhoneNumber();
        String date_en=getcurrentdate();
        String update1=getcurrentdate();
        String brand=r1.getVehicleBrand();
        String Vmodle = r1.getVehicleModel();
        String Vnumber = r1.getVehicleNumber();
        Cmilage = r1.getCurrentMilage();
        int Nmilage = r1.getNextServiceDueMilage();
        
       {
      try
            {
                  
              
                {
		String q3 = "INSERT INTO customer(cnic,cname,caddress,cemail,cphone,date,upto,cvbrand,cvmodel,cvnumber,ccmileage,cnmilage) VALUES ('"+nic+"', '"+ Cname +"' , '"+ Caddress +"' ,'"+Cemail+"' ,'"+  Cphone+"','"+date_en+"','"+update1+"','"+brand+"' , '"+ Vmodle +"','"+ Vnumber +"' , '"+ Cmilage+"' , '"+ Nmilage +"')";
                pst = con.prepareStatement(q3);
                pst.executeUpdate();}
                JOptionPane.showMessageDialog(null, "You have successfully added a Client");
                
                
            }
            catch (Exception e) 
            {
		System.out.println(e.getMessage());
            }
       
            tableload();
              
       }   
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed
    

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update");
        
        if(x==0)
        {
        String nic=nictxt.getText();
        String Cname = cname1.getText();
        String Caddress = caddress.getText();
        String Cemail = cemail.getText();
        String Cphone = cphone.getText();
        String update=getcurrentdate();
        String Vmodle = cmodel.getText();
        String brand=cbrand.getText();
        String Vnumber = vnumber.getText();
        int Cmilage = Integer.parseInt(cmilage.getText());
        int Nmilage = Cmilage + 5000;
        nmilage.setText(String.valueOf(Nmilage));
        
        
        
        try {
            
             String sql = "UPDATE customer SET cnic='"+nic+"', cname = '" +Cname + "', caddress = '" +Caddress + "' , cemail =  '" +Cemail + "', cphone = '" +Cphone + "',upto='"+ update +"', cvbrand = '" +brand +"',cvmodel='"+Vmodle+"', ccmileage = '" +Cmilage +"' , cnmilage = '" +Nmilage +"' where cvnumber = '" +Vnumber +"' ";
             pst = con.prepareStatement(sql);
             pst.execute();
             tableload();
            
            
        } catch (Exception e) {
            
            System.out.println(e.getMessage());
        }
        
        }
        
        nictxt.setText("");
        cname1.setText("");
        caddress.setText("");
        cemail.setText("");
        cphone.setText("");
        cbrand.setText("");
        cmodel.setText("");
        vnumber.setText("");
        cmilage.setText("");
        nmilage.setText("");
        
        
        tableload();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete the record");
        
        if(x==0)
        {
         
        String vnum = vnumber.getText();
        
        
        
        try {
            
             String sql = "DELETE FROM customer  where cvnumber = '" +vnum +"' ";
             pst = con.prepareStatement(sql);
             pst.execute();
             tableload();
            
            
        } catch (Exception e) {
            
            System.out.println(e.getMessage());
        }
        
        }
        
        nictxt.setText("");
        caddress.setText("");
        cemail.setText("");
        cphone.setText("");
        vnumber.setText("");
        cmilage.setText("");
        nmilage.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void infotable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infotable1MouseClicked
        int r = infotable1.getSelectedRow();
        String nic=infotable1.getValueAt(r, 0).toString();
        String nm = infotable1.getValueAt(r, 1).toString();
        String adrs = infotable1.getValueAt(r, 2).toString();
        String mail = infotable1.getValueAt(r, 3).toString();
        String phn = infotable1.getValueAt(r, 4).toString();
        String brnd=infotable1.getValueAt(r, 7).toString();
        String mdl = infotable1.getValueAt(r, 8).toString();
        String vnum = infotable1.getValueAt(r, 9).toString();
        String mlg = infotable1.getValueAt(r, 10).toString();
        
        
       
           
       
        nictxt.setText(nic);
        cname1.setText(nm);
        caddress.setText(adrs);
        cemail.setText(mail);
        cphone.setText(phn);
        cbrand.setText(brnd);
        cmodel.setText(mdl);
        vnumber.setText(vnum);
        cmilage.setText(mlg);
    }//GEN-LAST:event_infotable1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        main_gui main = new main_gui();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String a = search1.getText();
        
        try {
            String s2 =" SELECT cname,cvnumber,ccmileage FROM customer WHERE cvnumber = '"+a+"' ";
            pst = con.prepareStatement(s2);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmilageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmilageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cmilageKeyTyped

    private void nmilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmilageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmilageActionPerformed

    private void nmilageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmilageMouseClicked
        //nmilage.setText(String.valueOf(Nmilage));
    }//GEN-LAST:event_nmilageMouseClicked

    private void cname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cname1ActionPerformed

    private void cbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrandActionPerformed

    private void cmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmodelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_Reigstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_Reigstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_Reigstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_Reigstration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_Reigstration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cAddress;
    private javax.swing.JLabel cEmail;
    private javax.swing.JLabel cMilage;
    private javax.swing.JLabel cName;
    private javax.swing.JLabel cName1;
    private javax.swing.JLabel cPhone;
    private javax.swing.JLabel cPhone1;
    private javax.swing.JLabel cPhone2;
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField cbrand;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cmilage;
    private javax.swing.JTextField cmodel;
    private javax.swing.JTextField cname1;
    private javax.swing.JTextField cphone;
    private javax.swing.JTable infotable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nMilage;
    private javax.swing.JTextField nictxt;
    private javax.swing.JTextField nmilage;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JLabel vNumber;
    private javax.swing.JTextField vnumber;
    // End of variables declaration//GEN-END:variables
private String getcurrentdate(){
    DateFormat dat=new SimpleDateFormat("yyyy/MM/dd");
    Calendar cal=Calendar.getInstance();
    return(dat.format(cal.getTime()));
    
    
}



}
