/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import AutoMiraj.DBconnect.DBconnect;
import AutoMiraj.Controller.EstimationController;
import AutoMiraj.Model.Estimation;


/**
 *
 * @author USER
 */
public class CustomerDetails extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    
    
    public CustomerDetails() {
        initComponents();
        
        conn=DBconnect.connect();
        
        tableLoad();
    }

    
    
    public void tableLoad(){
        try{
            String sql="SELECT customerId, date, customerName, address, contact, nic, vehicleName, manufactureYear, vehicleNumber FROM customerdetails";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            customerTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cusNamebox = new javax.swing.JTextField();
        veNumberbox = new javax.swing.JTextField();
        cusAddressbox = new javax.swing.JTextField();
        manuYearbox = new javax.swing.JTextField();
        veNamebox = new javax.swing.JTextField();
        cusNicbox = new javax.swing.JTextField();
        contactbox = new javax.swing.JTextField();
        datebox = new javax.swing.JTextField();
        cusIdtxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "customer Id", "Date", "Customer Name", "Address", "Contact Number", "NIC", "Vehicle Name", "Manufacture Year", "Vehicle Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setRowHeight(30);
        customerTable.getTableHeader().setReorderingAllowed(false);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);
        if (customerTable.getColumnModel().getColumnCount() > 0) {
            customerTable.getColumnModel().getColumn(0).setResizable(false);
            customerTable.getColumnModel().getColumn(1).setResizable(false);
            customerTable.getColumnModel().getColumn(2).setResizable(false);
            customerTable.getColumnModel().getColumn(3).setResizable(false);
            customerTable.getColumnModel().getColumn(4).setResizable(false);
            customerTable.getColumnModel().getColumn(5).setResizable(false);
            customerTable.getColumnModel().getColumn(6).setResizable(false);
            customerTable.getColumnModel().getColumn(7).setResizable(false);
            customerTable.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 880, 330);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(900, 260, 110, 50);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(900, 190, 110, 50);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(900, 330, 110, 50);
        getContentPane().add(cusNamebox);
        cusNamebox.setBounds(210, 60, 100, 30);
        getContentPane().add(veNumberbox);
        veNumberbox.setBounds(780, 60, 110, 30);
        getContentPane().add(cusAddressbox);
        cusAddressbox.setBounds(310, 60, 90, 30);

        manuYearbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuYearboxActionPerformed(evt);
            }
        });
        getContentPane().add(manuYearbox);
        manuYearbox.setBounds(690, 60, 90, 30);

        veNamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veNameboxActionPerformed(evt);
            }
        });
        getContentPane().add(veNamebox);
        veNamebox.setBounds(590, 60, 100, 30);
        getContentPane().add(cusNicbox);
        cusNicbox.setBounds(500, 60, 90, 30);
        getContentPane().add(contactbox);
        contactbox.setBounds(400, 60, 100, 30);
        getContentPane().add(datebox);
        datebox.setBounds(120, 60, 90, 30);

        cusIdtxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cusIdtxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cusIdtxt);
        cusIdtxt.setBounds(30, 60, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InterfaceBackground.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1070, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        int r=customerTable.getSelectedRow();
        String cusId=customerTable.getValueAt(r, 0).toString();
        String date=customerTable.getValueAt(r, 1).toString();
        String cusName=customerTable.getValueAt(r, 2).toString();
        String cusAddress=customerTable.getValueAt(r, 3).toString();
        String contact=customerTable.getValueAt(r, 4).toString();
        String cusNic=customerTable.getValueAt(r, 5).toString();
        String veName=customerTable.getValueAt(r, 6).toString();
        String manuYear=customerTable.getValueAt(r, 7).toString();
        String veNumber=customerTable.getValueAt(r, 8).toString();
        
        datebox.setText(date);
        cusNamebox.setText(cusName);
        cusAddressbox.setText(cusAddress);
        contactbox.setText(contact);
        cusNicbox.setText(cusNic);
        veNamebox.setText(veName);
        manuYearbox.setText(manuYear);
        veNumberbox.setText(veNumber);
        cusIdtxt.setText(cusId);
        
        
    }//GEN-LAST:event_customerTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int delete=JOptionPane.showConfirmDialog(null, "Do you want to delete this?");
        
        if(delete==0){
            String name=cusNamebox.getText();
            
            
            try{
               int res=EstimationController.deleteCusDetails(name);
                if(res>0){
                    JOptionPane.showMessageDialog(this, "Delete success");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        tableLoad();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int update=JOptionPane.showConfirmDialog(null, "Do you want to really update?");
        if(update==0)
        {
            String cusId=cusIdtxt.getText();
            String date=datebox.getText();
            String cusName=cusNamebox.getText();
            String cusAddress=cusAddressbox.getText();
            String telNo=contactbox.getText();
            String cusNic=cusNicbox.getText();
            String veName=veNamebox.getText();
            String manuYear=manuYearbox.getText();
            String veNumber=veNumberbox.getText();
            
            
            try{
                Estimation estimation=new Estimation (cusId, date, cusName, cusAddress, telNo, cusNic, veName, manuYear, veNumber);
                int res= EstimationController.updateCusDetails(estimation);
            
                if(res>0){
                    JOptionPane.showMessageDialog(this,"Update success");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Update fail");
                }
            }
            
            
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        tableLoad();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void veNameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veNameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veNameboxActionPerformed

    private void manuYearboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuYearboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuYearboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactbox;
    private javax.swing.JTextField cusAddressbox;
    private javax.swing.JLabel cusIdtxt;
    private javax.swing.JTextField cusNamebox;
    private javax.swing.JTextField cusNicbox;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField datebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manuYearbox;
    private javax.swing.JTextField veNamebox;
    private javax.swing.JTextField veNumberbox;
    // End of variables declaration//GEN-END:variables
}
