/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class main_gui extends javax.swing.JFrame {

    
    
    login lg = new login();
    public static String uType = null;
    boolean grpMan = false;
    boolean grpData = false;
    boolean grpStock = false;
    
    public main_gui() {
        initComponents();
        this.levels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profitbtn = new javax.swing.JLabel();
        Financebtn = new javax.swing.JLabel();
        Registerbtn = new javax.swing.JLabel();
        Stockbtn = new javax.swing.JLabel();
        Aboutusbtn = new javax.swing.JLabel();
        Adminbtn = new javax.swing.JLabel();
        Employeebtn = new javax.swing.JLabel();
        Reservoirbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        Profitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profitbtn1.png"))); // NOI18N
        Profitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfitbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfitbtnMousePressed(evt);
            }
        });
        getContentPane().add(Profitbtn);
        Profitbtn.setBounds(320, 480, 150, 110);

        Financebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/financebtn1.png"))); // NOI18N
        Financebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FinancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FinancebtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FinancebtnMousePressed(evt);
            }
        });
        getContentPane().add(Financebtn);
        Financebtn.setBounds(300, 400, 150, 120);

        Registerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registerbtn1.png"))); // NOI18N
        Registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterbtnMousePressed(evt);
            }
        });
        getContentPane().add(Registerbtn);
        Registerbtn.setBounds(290, 340, 140, 110);

        Stockbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stocksupplybtn1.png"))); // NOI18N
        Stockbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StockbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StockbtnMouseReleased(evt);
            }
        });
        getContentPane().add(Stockbtn);
        Stockbtn.setBounds(270, 270, 150, 110);

        Aboutusbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenancebtn1.png"))); // NOI18N
        Aboutusbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutusbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutusbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutusbtnMousePressed(evt);
            }
        });
        getContentPane().add(Aboutusbtn);
        Aboutusbtn.setBounds(630, 480, 140, 110);

        Adminbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminbtn1.png"))); // NOI18N
        Adminbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Adminbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminbtnMousePressed(evt);
            }
        });
        getContentPane().add(Adminbtn);
        Adminbtn.setBounds(650, 410, 133, 100);

        Employeebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employeebtn1.png"))); // NOI18N
        Employeebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeebtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeebtnMousePressed(evt);
            }
        });
        getContentPane().add(Employeebtn);
        Employeebtn.setBounds(670, 330, 130, 110);

        Reservoirbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reservoirbtn1.png"))); // NOI18N
        Reservoirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservoirbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservoirbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservoirbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReservoirbtnMousePressed(evt);
            }
        });
        getContentPane().add(Reservoirbtn);
        Reservoirbtn.setBounds(680, 270, 140, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StockbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMouseEntered
        ImageIcon II1=new ImageIcon(getClass().getResource("/Images/stockbtn2.png"));
        Stockbtn.setIcon(II1);
    }//GEN-LAST:event_StockbtnMouseEntered

    private void StockbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMouseExited
        ImageIcon II1=new ImageIcon(getClass().getResource("/Images/stocksupplybtn1.png"));
        Stockbtn.setIcon(II1);
    }//GEN-LAST:event_StockbtnMouseExited

    private void StockbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMouseReleased
        ImageIcon II1=new ImageIcon(getClass().getResource("/Images/stocksupplybtn1.png"));
        Stockbtn.setIcon(II1);
    }//GEN-LAST:event_StockbtnMouseReleased

    private void RegisterbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbtnMouseEntered
       ImageIcon II2=new ImageIcon(getClass().getResource("/Images/registerbtn2.png"));
        Registerbtn.setIcon(II2);
    }//GEN-LAST:event_RegisterbtnMouseEntered

    private void RegisterbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbtnMouseExited
        ImageIcon II2=new ImageIcon(getClass().getResource("/Images/registerbtn1.png"));
        Registerbtn.setIcon(II2);
    }//GEN-LAST:event_RegisterbtnMouseExited

    private void RegisterbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterbtnMousePressed
        ImageIcon II2=new ImageIcon(getClass().getResource("/Images/registerbtn1.png"));
        Registerbtn.setIcon(II2);
        if(grpData == true || grpMan == true){
        
        }else{
            Client_Reigstration cr1=new Client_Reigstration();
            cr1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_RegisterbtnMousePressed

    private void FinancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinancebtnMouseEntered
        ImageIcon II2=new ImageIcon(getClass().getResource("/Images/financebtn2.png"));
        Financebtn.setIcon(II2);
    }//GEN-LAST:event_FinancebtnMouseEntered

    private void FinancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinancebtnMouseExited
        ImageIcon II3=new ImageIcon(getClass().getResource("/Images/financebtn1.png"));
        Financebtn.setIcon(II3);
    }//GEN-LAST:event_FinancebtnMouseExited

    private void FinancebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinancebtnMousePressed
        ImageIcon II3=new ImageIcon(getClass().getResource("/Images/financebtn1.png"));
        Financebtn.setIcon(II3);
        if(grpData == true || grpStock == true){
        
        }else{
            Bill_interface bill=new Bill_interface();
            bill.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_FinancebtnMousePressed

    private void ProfitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfitbtnMouseEntered
        ImageIcon II4=new ImageIcon(getClass().getResource("/Images/profitbtn2.png"));
        Profitbtn.setIcon(II4);
    }//GEN-LAST:event_ProfitbtnMouseEntered

    private void ProfitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfitbtnMouseExited
        ImageIcon II4=new ImageIcon(getClass().getResource("/Images/profitbtn1.png"));
        Profitbtn.setIcon(II4);
    }//GEN-LAST:event_ProfitbtnMouseExited

    private void ProfitbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfitbtnMousePressed
        ImageIcon II4=new ImageIcon(getClass().getResource("/Images/profitbtn1.png"));
        Profitbtn.setIcon(II4);
        if(grpData == true || grpStock == true){
        
        }else{
            Expense exp=new Expense();
            exp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ProfitbtnMousePressed

    private void ReservoirbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservoirbtnMouseEntered
       ImageIcon II5=new ImageIcon(getClass().getResource("/Images/reservoirbtn2.png"));
        Reservoirbtn.setIcon(II5);
    }//GEN-LAST:event_ReservoirbtnMouseEntered

    private void ReservoirbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservoirbtnMouseExited
        ImageIcon II5=new ImageIcon(getClass().getResource("/Images/reservoirbtn1.png"));
        Reservoirbtn.setIcon(II5);
        
    }//GEN-LAST:event_ReservoirbtnMouseExited

    private void ReservoirbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservoirbtnMousePressed
        ImageIcon II5=new ImageIcon(getClass().getResource("/Images/reservoirbtn1.png"));
        Reservoirbtn.setIcon(II5);
        
        if(grpMan == true || grpData == true){
            
        }
        else{
            Reservoir res=new Reservoir();
            res.setVisible(true);
            this.dispose();
        }
        
        Reservoir R1=new Reservoir();
        R1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReservoirbtnMousePressed

    private void EmployeebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeebtnMouseEntered
        ImageIcon II6=new ImageIcon(getClass().getResource("/Images/employeebtn2.png"));
        Employeebtn.setIcon(II6);
    }//GEN-LAST:event_EmployeebtnMouseEntered

    private void EmployeebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeebtnMouseExited
        ImageIcon II6=new ImageIcon(getClass().getResource("/Images/employeebtn1.png"));
        Employeebtn.setIcon(II6);
    }//GEN-LAST:event_EmployeebtnMouseExited

    private void EmployeebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeebtnMousePressed
        ImageIcon II6=new ImageIcon(getClass().getResource("/Images/employeebtn1.png"));
        Employeebtn.setIcon(II6);
        if(grpMan == true || grpStock == true){
        
        }else{
            emply emp=new emply();
            emp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_EmployeebtnMousePressed

    private void AdminbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminbtnMouseEntered
        ImageIcon II7=new ImageIcon(getClass().getResource("/Images/adminbtn2.png"));
        Adminbtn.setIcon(II7);
    }//GEN-LAST:event_AdminbtnMouseEntered

    private void AdminbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminbtnMouseExited
        ImageIcon II7=new ImageIcon(getClass().getResource("/Images/adminbtn1.png"));
        Adminbtn.setIcon(II7);
    }//GEN-LAST:event_AdminbtnMouseExited

    private void AdminbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminbtnMousePressed
        ImageIcon II7=new ImageIcon(getClass().getResource("/Images/adminbtn1.png"));
        Adminbtn.setIcon(II7);
        if(grpData == true || grpStock == true || grpMan == true){
        
        }else{
            Admin_int ad = new Admin_int();
            ad.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AdminbtnMousePressed

    private void AboutusbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusbtnMouseEntered
        ImageIcon II8=new ImageIcon(getClass().getResource("/Images/maintenancebtn2.png"));
        Aboutusbtn.setIcon(II8);
    }//GEN-LAST:event_AboutusbtnMouseEntered

    private void AboutusbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusbtnMouseExited
       ImageIcon II8=new ImageIcon(getClass().getResource("/Images/maintenancebtn1.png"));
        Aboutusbtn.setIcon(II8);
    }//GEN-LAST:event_AboutusbtnMouseExited

    private void AboutusbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusbtnMousePressed
         ImageIcon II8=new ImageIcon(getClass().getResource("/Images/maintenancebtn1.png"));
        Aboutusbtn.setIcon(II8);
        if(grpMan == true || grpStock == true){
        
        }else{
            Maintenance m = new Maintenance();
            m.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_AboutusbtnMousePressed

    private void ReservoirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservoirbtnMouseClicked
        Reservoir R1=new Reservoir();
        R1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReservoirbtnMouseClicked

    private void StockbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMousePressed
        // TODO add your handling code here:
        if(grpData == true || grpMan == true){
        
        }else{
            Stock sto=new Stock();
            sto.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_StockbtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutusbtn;
    private javax.swing.JLabel Adminbtn;
    private javax.swing.JLabel Employeebtn;
    private javax.swing.JLabel Financebtn;
    private javax.swing.JLabel Profitbtn;
    private javax.swing.JLabel Registerbtn;
    private javax.swing.JLabel Reservoirbtn;
    private javax.swing.JLabel Stockbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

public void levels(){
        String userType = uType;
        
        if (userType.equals("Manager")){
            grpMan = true;
            Reservoirbtn.disable();
            Employeebtn.disable();
            Adminbtn.disable();
            Aboutusbtn.disable();
            Stockbtn.disable();
            Registerbtn.disable();
        }
        if (userType.equals("Data Entry Operator")){
            grpData = true;
            Financebtn.disable();
            Profitbtn.disable();
            Stockbtn.disable();
            Adminbtn.disable();
        }
        if (userType.equals("Stock Manager")){
            grpStock = true;
            Reservoirbtn.disable();
            Employeebtn.disable();
            Adminbtn.disable();
            Aboutusbtn.disable();
            Registerbtn.disable();
            Financebtn.disable();  
            Profitbtn.disable();
        }
        
    }

}
