/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import AutoMiraj.Controller.DBAccess_Rumi;
import AutoMiraj.DBconnect.DBconnect;
import AutoMiraj.View.main_gui;
//import static Interfaces.Manage_Users.rs;
import java.awt.Color;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rumesha
 */
public class Maintenance extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement ps = null;
    static ResultSet rs = null;
    DBAccess_Rumi rm = new DBAccess_Rumi();
    
   
    
    
    public Maintenance() {
        initComponents();
        conn = DBconnect.connect();
        tableLoad();
        fillCombo();
    }
    
    public void tableLoad(){
        
        try{
        String sql = "select machine_id,service_date,machine_name,additional_parts,mechanic_details,remarks,cost from maintenance";
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();
        tbl_maintenance.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch (Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_machineIDSerch = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        btn_clearM = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_maintenance = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_machineID = new javax.swing.JLabel();
        lbl_serviceDate = new javax.swing.JLabel();
        lbl_cat = new javax.swing.JLabel();
        txt_cost1 = new javax.swing.JTextField();
        lbl_additionalParts = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_additionalParts = new javax.swing.JTextArea();
        lbl_mechanicDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area_mechanicDetails = new javax.swing.JTextArea();
        lbl_remarks = new javax.swing.JLabel();
        lbl_cost = new javax.swing.JLabel();
        txt_cost = new javax.swing.JTextField();
        lbl_cost1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_area_remarks1 = new javax.swing.JTextArea();
        txt_mac_name = new javax.swing.JTextField();
        service_DateChooser = new com.toedter.calendar.JDateChooser();
        cmb_machineID = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maintenance");
        getContentPane().setLayout(null);

        txt_machineIDSerch.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txt_machineIDSerch.setForeground(new java.awt.Color(153, 153, 153));
        txt_machineIDSerch.setText("Machine ID");
        txt_machineIDSerch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_machineIDSerch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_machineIDSerch.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        txt_machineIDSerch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_machineIDSerchMouseClicked(evt);
            }
        });
        txt_machineIDSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_machineIDSerchActionPerformed(evt);
            }
        });
        getContentPane().add(txt_machineIDSerch);
        txt_machineIDSerch.setBounds(560, 130, 148, 33);

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search);
        btn_search.setBounds(750, 130, 100, 33);

        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_insert);
        btn_insert.setBounds(140, 570, 80, 30);

        btn_clearM.setText("Clear");
        btn_clearM.setActionCommand("Delete");
        btn_clearM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearMActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clearM);
        btn_clearM.setBounds(250, 570, 80, 30);

        tbl_maintenance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Machine ID", "Service Date", "Category", "Additional parts ", "Remarks", "Mechanic Details", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbl_maintenance);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(430, 170, 520, 330);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 570, 70, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert Maintenance Details", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        lbl_machineID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_machineID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_machineID.setText("Machine ID");
        jPanel1.add(lbl_machineID);
        lbl_machineID.setBounds(30, 30, 89, 15);

        lbl_serviceDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_serviceDate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_serviceDate.setText("Service Date");
        jPanel1.add(lbl_serviceDate);
        lbl_serviceDate.setBounds(30, 110, 89, 20);

        lbl_cat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cat.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cat.setText("Machine Name");
        jPanel1.add(lbl_cat);
        lbl_cat.setBounds(30, 70, 89, 20);
        jPanel1.add(txt_cost1);
        txt_cost1.setBounds(140, 470, 166, 30);

        lbl_additionalParts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_additionalParts.setForeground(new java.awt.Color(255, 255, 255));
        lbl_additionalParts.setText("Additional Parts");
        jPanel1.add(lbl_additionalParts);
        lbl_additionalParts.setBounds(30, 180, 89, 15);

        txtArea_additionalParts.setColumns(20);
        txtArea_additionalParts.setRows(5);
        jScrollPane1.setViewportView(txtArea_additionalParts);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 150, 166, 85);

        lbl_mechanicDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_mechanicDetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mechanicDetails.setText("Mechanic Details");
        jPanel1.add(lbl_mechanicDetails);
        lbl_mechanicDetails.setBounds(30, 280, 89, 15);

        txt_area_mechanicDetails.setColumns(20);
        txt_area_mechanicDetails.setRows(5);
        jScrollPane2.setViewportView(txt_area_mechanicDetails);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(140, 260, 166, 85);

        lbl_remarks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_remarks.setForeground(new java.awt.Color(255, 255, 255));
        lbl_remarks.setText("Remarks");
        jPanel1.add(lbl_remarks);
        lbl_remarks.setBounds(30, 410, 89, 15);

        lbl_cost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cost.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cost.setText("Cost");
        jPanel1.add(lbl_cost);
        lbl_cost.setBounds(80, 540, 89, 15);
        jPanel1.add(txt_cost);
        txt_cost.setBounds(190, 530, 166, 20);

        lbl_cost1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cost1.setText("Cost");
        jPanel1.add(lbl_cost1);
        lbl_cost1.setBounds(30, 480, 50, 14);

        txt_area_remarks1.setColumns(20);
        txt_area_remarks1.setRows(5);
        jScrollPane5.setViewportView(txt_area_remarks1);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(140, 370, 166, 85);

        txt_mac_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mac_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_mac_name);
        txt_mac_name.setBounds(140, 70, 166, 30);

        service_DateChooser.setDateFormatString("yyyy-MM-dd"); // NOI18N
        jPanel1.add(service_DateChooser);
        service_DateChooser.setBounds(140, 110, 170, 30);

        cmb_machineID.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_machineIDPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmb_machineID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_machineIDMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmb_machineIDMouseExited(evt);
            }
        });
        cmb_machineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_machineIDActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_machineID);
        cmb_machineID.setBounds(140, 30, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 60, 360, 510);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundNew.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_machineIDSerchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_machineIDSerchMouseClicked
        txt_machineIDSerch.setText("");
        txt_machineIDSerch.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_txt_machineIDSerchMouseClicked

    private void txt_machineIDSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_machineIDSerchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_machineIDSerchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main_gui M=new main_gui();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       String name = txt_machineIDSerch.getText();
       String sql = "select machine_id,service_date,machine_name,additional_parts,mechanic_details,remarks,cost from maintenance where machine_id LIKE '%"+ name+"%'";
       try {
       ps = conn.prepareStatement(sql);
       rs = ps.executeQuery();
       
       tbl_maintenance.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch (Exception e){
       }
       
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        SimpleDateFormat sdf= new SimpleDateFormat("YYYY-MM-dd");
        Date temp = service_DateChooser.getDate();
        String s_date = sdf.format(temp);
        
        String machineId = cmb_machineID.getSelectedItem().toString();
        String name = txt_mac_name.getText();
        String add_parts = txtArea_additionalParts.getText();
        String mec_detail = txt_area_mechanicDetails.getText();
        String remarks1 = txt_area_remarks1.getText();
        String cost1 = txt_cost1.getText();
         
        try{
        rm.insertMaintenance(machineId, s_date, name, add_parts, mec_detail, remarks1,cost1);
        tableLoad();
            
        }
        catch (Exception e){
        }

    }//GEN-LAST:event_btn_insertActionPerformed

    private void fillCombo(){
        try{
            String sql = "select * from machines";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while (rs.next()){
                String id = rs.getString("machine_id");
                cmb_machineID.addItem(id);
            }
        }
        
        catch (Exception e){
        }
    }
    private void btn_clearMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearMActionPerformed
        cmb_machineID.setName("");
        service_DateChooser.setDate(null);
        txt_mac_name.setText("");
        txtArea_additionalParts.setText("");
        txt_area_mechanicDetails.setText("");
        txt_area_remarks1.setText("");
        txt_cost1.setText("");
        
    }//GEN-LAST:event_btn_clearMActionPerformed
      
    
       
    private void cmb_machineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_machineIDActionPerformed
         
       
        
    }//GEN-LAST:event_cmb_machineIDActionPerformed
 
    private void txt_mac_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mac_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mac_nameActionPerformed

    private void cmb_machineIDPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_machineIDPopupMenuWillBecomeInvisible
        try{
            String temp = (String)cmb_machineID.getSelectedItem();
            String sql = "select * from machines where machine_id='"+temp+"' ";
            ps = conn.prepareStatement(sql);
            //ps.setString(2,temp);
            rs = ps.executeQuery();
            
            while (rs.next()){
                String a = rs.getString("machine_name");
                txt_mac_name.setText(a);
            }
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_cmb_machineIDPopupMenuWillBecomeInvisible

    private void cmb_machineIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_machineIDMouseExited
       //Action will perform once the mouse move away from the object 
        
    }//GEN-LAST:event_cmb_machineIDMouseExited

    private void cmb_machineIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_machineIDMouseClicked
         
    }//GEN-LAST:event_cmb_machineIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maintenance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintenance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clearM;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cmb_machineID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_additionalParts;
    private javax.swing.JLabel lbl_cat;
    private javax.swing.JLabel lbl_cost;
    private javax.swing.JLabel lbl_cost1;
    private javax.swing.JLabel lbl_machineID;
    private javax.swing.JLabel lbl_mechanicDetails;
    private javax.swing.JLabel lbl_remarks;
    private javax.swing.JLabel lbl_serviceDate;
    private com.toedter.calendar.JDateChooser service_DateChooser;
    private javax.swing.JTable tbl_maintenance;
    private javax.swing.JTextArea txtArea_additionalParts;
    private javax.swing.JTextArea txt_area_mechanicDetails;
    private javax.swing.JTextArea txt_area_remarks1;
    private javax.swing.JTextField txt_cost;
    private javax.swing.JTextField txt_cost1;
    private javax.swing.JTextField txt_mac_name;
    private javax.swing.JTextField txt_machineIDSerch;
    // End of variables declaration//GEN-END:variables
}
