/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoMiraj.View;

import java.text.SimpleDateFormat;
import java.util.Date;
import AutoMiraj.Controller.DBAccess_Rumi;
import AutoMiraj.DBconnect.DBconnect;
import AutoMiraj.View.main_gui;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rumesha
 */
public class scheduling extends javax.swing.JFrame {
    static Connection conn = DBconnect.connect();
    static PreparedStatement ps = null;
    static Statement st = null;
    static ResultSet rs = null;
    DBAccess_Rumi rm = new DBAccess_Rumi(); 
    String time = null;
    
    
    
    
    public scheduling() {
        initComponents();
        conn = DBconnect.connect();
        
        //rm.deleteData();
        
     //this.copyDetails();
    }
    public void tableLoad2(){
        
        try{
        SimpleDateFormat sdf1 = new SimpleDateFormat("YYYY-MM-dd");
        Date temp = dc_dateRemove.getDate();
        String date = sdf1.format(temp);
        rs = rm.getUnavailableEmp(date);
        tbl_removeSchedule.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch (Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s_type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        dc_date = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_sc_back = new javax.swing.JButton();
        time1 = new javax.swing.JRadioButton();
        time2 = new javax.swing.JRadioButton();
        time3 = new javax.swing.JRadioButton();
        time4 = new javax.swing.JRadioButton();
        time5 = new javax.swing.JRadioButton();
        time6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        day = new javax.swing.JRadioButton();
        night = new javax.swing.JRadioButton();
        btn_remove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_removeSchedule = new javax.swing.JTable();
        r_time1 = new javax.swing.JCheckBox();
        r_time2 = new javax.swing.JCheckBox();
        r_time3 = new javax.swing.JCheckBox();
        r_time4 = new javax.swing.JCheckBox();
        r_time5 = new javax.swing.JCheckBox();
        r_time6 = new javax.swing.JCheckBox();
        dc_dateRemove = new com.toedter.calendar.JDateChooser();
        btn_view_appoinment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Scheduling");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 60, 250, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Service Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 140, 40);

        s_type.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        s_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car Wash", "Repair", "Full_service" }));
        s_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_typeActionPerformed(evt);
            }
        });
        getContentPane().add(s_type);
        s_type.setBounds(220, 210, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 280, 70, 16);

        dc_date.setName("dc_date"); // NOI18N
        getContentPane().add(dc_date);
        dc_date.setBounds(220, 270, 140, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 320, 250, 260);

        btn_sc_back.setText("Back");
        btn_sc_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sc_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sc_back);
        btn_sc_back.setBounds(270, 660, 55, 23);

        time1.setBackground(new java.awt.Color(0, 0, 0));
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("8.00 - 10.00");
        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        getContentPane().add(time1);
        time1.setBounds(400, 330, 100, 23);

        time2.setBackground(new java.awt.Color(0, 0, 0));
        time2.setForeground(new java.awt.Color(255, 255, 255));
        time2.setText("10.00 - 12.00");
        time2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time2ActionPerformed(evt);
            }
        });
        getContentPane().add(time2);
        time2.setBounds(400, 360, 100, 23);

        time3.setBackground(new java.awt.Color(0, 0, 0));
        time3.setForeground(new java.awt.Color(255, 255, 255));
        time3.setText("13.00 - 15.00");
        time3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time3ActionPerformed(evt);
            }
        });
        getContentPane().add(time3);
        time3.setBounds(400, 390, 100, 23);

        time4.setBackground(new java.awt.Color(0, 0, 0));
        time4.setForeground(new java.awt.Color(255, 255, 255));
        time4.setText("15.00 - 17.00");
        time4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time4ActionPerformed(evt);
            }
        });
        getContentPane().add(time4);
        time4.setBounds(400, 420, 100, 23);

        time5.setBackground(new java.awt.Color(0, 0, 0));
        time5.setForeground(new java.awt.Color(255, 255, 255));
        time5.setText("17.00 - 19.00");
        time5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time5ActionPerformed(evt);
            }
        });
        getContentPane().add(time5);
        time5.setBounds(400, 450, 100, 23);

        time6.setBackground(new java.awt.Color(0, 0, 0));
        time6.setForeground(new java.awt.Color(255, 255, 255));
        time6.setText("20.00 - 22.00");
        time6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time6ActionPerformed(evt);
            }
        });
        getContentPane().add(time6);
        time6.setBounds(400, 480, 100, 23);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 270, 90, 30);

        jButton2.setText("Add schedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 510, 100, 40);

        day.setBackground(new java.awt.Color(0, 0, 0));
        day.setForeground(new java.awt.Color(255, 255, 255));
        day.setText("Day");
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        getContentPane().add(day);
        day.setBounds(380, 220, 45, 23);

        night.setBackground(new java.awt.Color(0, 0, 0));
        night.setForeground(new java.awt.Color(255, 255, 255));
        night.setText("Night");
        night.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightActionPerformed(evt);
            }
        });
        getContentPane().add(night);
        night.setBounds(440, 220, 51, 23);

        btn_remove.setText("Remove Schedule");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_remove);
        btn_remove.setBounds(1110, 540, 130, 30);

        tbl_removeSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_removeSchedule);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(530, 320, 570, 260);

        r_time1.setBackground(new java.awt.Color(0, 0, 0));
        r_time1.setForeground(new java.awt.Color(255, 255, 255));
        r_time1.setText("8.00-10.00");
        getContentPane().add(r_time1);
        r_time1.setBounds(1110, 310, 90, 23);

        r_time2.setBackground(new java.awt.Color(0, 0, 0));
        r_time2.setForeground(new java.awt.Color(255, 255, 255));
        r_time2.setText("10.00-12.00");
        getContentPane().add(r_time2);
        r_time2.setBounds(1110, 350, 90, 23);

        r_time3.setBackground(new java.awt.Color(0, 0, 0));
        r_time3.setForeground(new java.awt.Color(255, 255, 255));
        r_time3.setText("13.00-15.00");
        getContentPane().add(r_time3);
        r_time3.setBounds(1110, 390, 90, 23);

        r_time4.setBackground(new java.awt.Color(0, 0, 0));
        r_time4.setForeground(new java.awt.Color(255, 255, 255));
        r_time4.setText("15.00-17.00");
        getContentPane().add(r_time4);
        r_time4.setBounds(1110, 430, 90, 23);

        r_time5.setBackground(new java.awt.Color(0, 0, 0));
        r_time5.setForeground(new java.awt.Color(255, 255, 255));
        r_time5.setText("17.00-19.00");
        getContentPane().add(r_time5);
        r_time5.setBounds(1110, 470, 90, 23);

        r_time6.setBackground(new java.awt.Color(0, 0, 0));
        r_time6.setForeground(new java.awt.Color(255, 255, 255));
        r_time6.setText("20.00-22.00");
        getContentPane().add(r_time6);
        r_time6.setBounds(1110, 510, 90, 23);
        getContentPane().add(dc_dateRemove);
        dc_dateRemove.setBounds(650, 260, 170, 30);

        btn_view_appoinment.setText("View Appoinments");
        btn_view_appoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_appoinmentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view_appoinment);
        btn_view_appoinment.setBounds(860, 260, 130, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundNew.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sc_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sc_backActionPerformed
        main_gui M=new main_gui();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sc_backActionPerformed

    private void s_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_typeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String type = s_type.getSelectedItem().toString();
        SimpleDateFormat sdf= new SimpleDateFormat("YYYY-MM-dd");
        Date temp = dc_date.getDate();
        String date = sdf.format(temp);
        
        //rs = rm.getAvailableEmp(type, date, time);
        
        if(day.isSelected() && time1.isSelected() == false && time2.isSelected() == false && time3.isSelected() == false){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
        }
        
        if(night.isSelected() && time4.isSelected() == false && time5.isSelected() == false && time6.isSelected() == false){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
        }
        
        if(time1.isSelected()){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and 8To10<>'1' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
            
        }
        if(time2.isSelected()){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and tenTo12<>'1' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
        }
        if(time3.isSelected()){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and oneTo3<>'1' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
        }
        if(time4.isSelected()){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and threeTo5<>'1' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
        }
        if(time5.isSelected()){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and fiveTo7<>'1' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
        }
        if(time6.isSelected()){
            try{
                String sql;
                sql = "Select username from appoinment where time = '"+time+"' and Date = '"+date+"' and eightTo20<>'1' and WorkType = '"+type+"'";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
            
            }catch(Exception e){
            
            }
            
        }
        
        try{
            if(rs.next()){
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightActionPerformed
        day.setSelected(false);
        
        time = "Night";
        time1.setVisible(false);
        time2.setVisible(false);
        time3.setVisible(false);
          
        time4.setVisible(true);
        time5.setVisible(true);
        time6.setVisible(true);
        
        if(day.isSelected() == false && night.isSelected() == false){
            time = "";
            time1.setVisible(true);
            time2.setVisible(true);
            time3.setVisible(true);
            time4.setVisible(true);
            time5.setVisible(true);
            time6.setVisible(true);
        }
    }//GEN-LAST:event_nightActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        night.setSelected(false);
        
        time = "day";
        time4.setVisible(false);
        time5.setVisible(false);
        time6.setVisible(false);
            
        time1.setVisible(true);
        time2.setVisible(true);
        time3.setVisible(true);
        
        if(day.isSelected() == false && night.isSelected() == false){
            time = "";
            time1.setVisible(true);
            time2.setVisible(true);
            time3.setVisible(true);
            time4.setVisible(true);
            time5.setVisible(true);
            time6.setVisible(true);
        }
    }//GEN-LAST:event_dayActionPerformed

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
        time2.setSelected(false);
        time3.setSelected(false);
        
    }//GEN-LAST:event_time1ActionPerformed

    private void time2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time2ActionPerformed
        time1.setSelected(false);
        time3.setSelected(false);
    }//GEN-LAST:event_time2ActionPerformed

    private void time3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time3ActionPerformed
        time2.setSelected(false);
        time1.setSelected(false);
    }//GEN-LAST:event_time3ActionPerformed

    private void time4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time4ActionPerformed
        time5.setSelected(false);
        time6.setSelected(false);
    }//GEN-LAST:event_time4ActionPerformed

    private void time5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time5ActionPerformed
        time4.setSelected(false);
        time6.setSelected(false);
    }//GEN-LAST:event_time5ActionPerformed

    private void time6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time6ActionPerformed
        time4.setSelected(false);
        time5.setSelected(false);
    }//GEN-LAST:event_time6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        String user_name = jTable1.getValueAt(row, 0).toString();
        
        SimpleDateFormat sdf= new SimpleDateFormat("YYYY-MM-dd");
        Date temp = dc_date.getDate();
        String date = sdf.format(temp);
        
        if(time1.isSelected()){
            try{
                String sql;
                sql = "update appoinment set 8To10 = ? where username = '"+user_name+"' and Date = '"+date+"'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "1");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(time2.isSelected()){
            try{
                String sql;
                sql = "update appoinment set tenTo12 = ? where username = '"+user_name+"' and Date = '"+date+"'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "1");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(time3.isSelected()){
            try{
                String sql;
                sql = "update appoinment set oneTo3 = ? where username = '"+user_name+"' and Date = '"+date+"'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "1");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(time4.isSelected()){
            try{
                String sql;
                sql = "update appoinment set threeTo5 = ? where username = '"+user_name+"' and Date = '"+date+"'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "1");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(time5.isSelected()){
            try{
                String sql;
                sql = "update appoinment set fiveTo7 = ? where username = '"+user_name+"' and Date = '"+date+"'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "1");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(time6.isSelected()){
            try{
                String sql;
                sql = "update appoinment set eightTo20 = ? where username = '"+user_name+"' and Date = '"+date+"'";
                ps = conn.prepareStatement(sql);
                ps.setString(1, "1");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        int row1 = tbl_removeSchedule.getSelectedRow();
        String user_name1 = tbl_removeSchedule.getValueAt(row1, 1).toString();
        
        SimpleDateFormat sdf= new SimpleDateFormat("YYYY-MM-dd");
        Date temp = dc_dateRemove.getDate();
        String date1 = sdf.format(temp);
        
        //System.out.println(user_name1);
        
       
        if(r_time1.isSelected()){
            try{
                String sql1;
                sql1 = "update appoinment set 8To10 = ? where username = '"+user_name1+"' and Date = '"+date1+"'";
                ps = conn.prepareStatement(sql1);
                ps.setString(1, "0");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        
        if(r_time2.isSelected()){
            try{
                String sql1;
                sql1 = "update appoinment set tenTo12 = ? where username = '"+user_name1+"' and Date = '"+date1+"'";
                ps = conn.prepareStatement(sql1);
                ps.setString(1, "0");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(r_time3.isSelected()){
            try{
                String sql1;
                sql1 = "update appoinment set oneTo3 = ? where username = '"+user_name1+"' and Date = '"+date1+"'";
                ps = conn.prepareStatement(sql1);
                ps.setString(1, "0");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(r_time4.isSelected()){
            try{
                String sql1;
                sql1 = "update appoinment set threeTo5 = ? where username = '"+user_name1+"' and Date = '"+date1+"'";
                ps = conn.prepareStatement(sql1);
                ps.setString(1, "0");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(r_time5.isSelected()){
            try{
                String sql1;
                sql1 = "update appoinment set fiveTo7 = ? where username = '"+user_name1+"' and Date = '"+date1+"'";
                ps = conn.prepareStatement(sql1);
                ps.setString(1, "0");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
        if(r_time6.isSelected()){
            try{
                String sql1;
                sql1 = "update appoinment set eightTo20 = ? where username = '"+user_name1+"' and Date = '"+date1+"'";
                ps = conn.prepareStatement(sql1);
                ps.setString(1, "0");
                ps.execute();
            
            }catch(Exception e){
            
            }
        }
         tableLoad2(); 
        
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_view_appoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_appoinmentActionPerformed
        tableLoad2();  
        
    }//GEN-LAST:event_btn_view_appoinmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_sc_back;
    private javax.swing.JButton btn_view_appoinment;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton day;
    private com.toedter.calendar.JDateChooser dc_date;
    private com.toedter.calendar.JDateChooser dc_dateRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton night;
    private javax.swing.JCheckBox r_time1;
    private javax.swing.JCheckBox r_time2;
    private javax.swing.JCheckBox r_time3;
    private javax.swing.JCheckBox r_time4;
    private javax.swing.JCheckBox r_time5;
    private javax.swing.JCheckBox r_time6;
    private javax.swing.JComboBox s_type;
    private javax.swing.JTable tbl_removeSchedule;
    private javax.swing.JRadioButton time1;
    private javax.swing.JRadioButton time2;
    private javax.swing.JRadioButton time3;
    private javax.swing.JRadioButton time4;
    private javax.swing.JRadioButton time5;
    private javax.swing.JRadioButton time6;
    // End of variables declaration//GEN-END:variables

    public void copyDetails(){
        String name = null;
        String time = null;
        String date = null;
        String type = null;
        try{
            rs = rm.gettingDetails();
            while(rs.next()){
                date = rs.getString("Date");
                name = rs.getString("emp_name");
                time = rs.getString("Time");
                type = rs.getString("emp_work_type");
                
                this.saveDetails(name, time, date, type);
                
            }
        }catch(Exception e){
            
        }  
    }
    public void saveDetails(String n, String t, String d, String type){
        //System.out.println(n +" "+ t);
        rm.saveDetails(n,t,d,type);
    }
}
